// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEA3v8_H6zqbvEfUyNbP29lVTsymNmuE',
    appId: '1:32164125946:web:82aa40a3e4e579f76dfd43',
    messagingSenderId: '32164125946',
    projectId: 'what-the-fed',
    authDomain: 'whatthefed.firebaseapp.com',
    storageBucket: 'whatthefed.firebasestorage.app',
    measurementId: 'G-G0MF04KTYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezNofigmAJ4z3dZm1vAs0A6uaj8nP9H4',
    appId: '1:32164125946:android:24e68deba5e9bb496dfd43',
    messagingSenderId: '32164125946',
    projectId: 'what-the-fed',
    storageBucket: 'what-the-fed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADT7Ylh3iaJbnoPa1_zbGELi3X-j4doD8',
    appId: '1:32164125946:ios:a48683c2344faca46dfd43',
    messagingSenderId: '32164125946',
    projectId: 'what-the-fed',
    storageBucket: 'what-the-fed.firebasestorage.app',
    iosBundleId: 'com.example.civicProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADT7Ylh3iaJbnoPa1_zbGELi3X-j4doD8',
    appId: '1:32164125946:ios:a48683c2344faca46dfd43',
    messagingSenderId: '32164125946',
    projectId: 'what-the-fed',
    storageBucket: 'what-the-fed.firebasestorage.app',
    iosBundleId: 'com.example.civicProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwEA3v8_H6zqbvEfUyNbP29lVTsymNmuE',
    appId: '1:32164125946:web:3b0bdfd5f451f5266dfd43',
    messagingSenderId: '32164125946',
    projectId: 'what-the-fed',
    authDomain: 'what-the-fed.firebaseapp.com',
    storageBucket: 'what-the-fed.firebasestorage.app',
    measurementId: 'G-F24G2PRPJT',
  );

}